name: Prettier
on: pull_request
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - run: npm install

      - run: npx prettier --check ./app
